#!/bin/sh
ALL=1
COMPASS=0
BSC=0
OPTIMIZE=0
CLEANUP=0
while test $# -gt 0
do
    case "$1" in
        all) ALL=1
            ;;
        compass) COMPASS=1 ; ALL=0
            ;;
        bsc) BSC=1 ; ALL=0
            ;;
        optimize) OPTIMIZE=1 ; ALL=0
            ;;
        cleanup) CLEANUP=1
    esac
    shift
done

if [ "$CLEANUP" == 1 ]; then
    ./clean
fi

if [ "$ALL" == 1 ] || [ "$BSC" == 1 ]; then
	echo BSC BUILD...
	bsc build
	echo OK
fi

if [ "$ALL" == 1 ] || [ "$COMPASS" == 1 ]; then
	echo COMPASS BUILD DEV
	compass compile
	echo OK
fi

if [ "$ALL" == 1 ] || [ "$OPTIMIZATION" == 1 ]; then
	echo JS OPTIMIZATION
	node optimize.js
	echo OK
fi